# Generated by Django 6.1.1 on 2026-09-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin', ''), _negated=True), fields=('gstin',), name='one_customer_per_gstin'),
        ),
    ]
