# Generated by Django 6.1.1 on 2026-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_one_customer_per_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
