# Generated by Django 6.1.1 on 2026-09-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'permissions': [('archive_customer', 'Can archive customer')]},
        ),
    ]
