# Generated by Django 6.1.1 on 2026-09-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0007_archived_items'),
        ('purchases', '0005_service_and_one_off_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cost_per_stock_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalogue.item')),
                ('purchase_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='purchases.purchaseline')),
            ],
            options={
                'ordering': ('-date', '-pk'),
            },
        ),
    ]
