from django.db import models


class UQC(models.TextChoices):
    """The GST unit quantity codes, which returns report every quantity in.

    A unit outside this list is rejected when a GSTR-1 HSN summary or an
    e-invoice is filed, so an Item's units are chosen from it rather than typed.
    """

    BAG = "BAG", "BAG · Bags"
    BAL = "BAL", "BAL · Bale"
    BDL = "BDL", "BDL · Bundles"
    BKL = "BKL", "BKL · Buckles"
    BOU = "BOU", "BOU · Billions of units"
    BOX = "BOX", "BOX · Box"
    BTL = "BTL", "BTL · Bottles"
    BUN = "BUN", "BUN · Bunches"
    CAN = "CAN", "CAN · Cans"
    CBM = "CBM", "CBM · Cubic metres"
    CCM = "CCM", "CCM · Cubic centimetres"
    CMS = "CMS", "CMS · Centimetres"
    CTN = "CTN", "CTN · Cartons"
    DOZ = "DOZ", "DOZ · Dozens"
    DRM = "DRM", "DRM · Drums"
    GGK = "GGK", "GGK · Great gross"
    GMS = "GMS", "GMS · Grammes"
    GRS = "GRS", "GRS · Gross"
    GYD = "GYD", "GYD · Gross yards"
    KGS = "KGS", "KGS · Kilograms"
    KLR = "KLR", "KLR · Kilolitres"
    KME = "KME", "KME · Kilometres"
    LTR = "LTR", "LTR · Litres"
    MLT = "MLT", "MLT · Millilitres"
    MTR = "MTR", "MTR · Metres"
    MTS = "MTS", "MTS · Metric tons"
    NOS = "NOS", "NOS · Numbers"
    OTH = "OTH", "OTH · Others"
    PAC = "PAC", "PAC · Packs"
    PCS = "PCS", "PCS · Pieces"
    PRS = "PRS", "PRS · Pairs"
    QTL = "QTL", "QTL · Quintals"
    ROL = "ROL", "ROL · Rolls"
    SET = "SET", "SET · Sets"
    SQF = "SQF", "SQF · Square feet"
    SQM = "SQM", "SQM · Square metres"
    SQY = "SQY", "SQY · Square yards"
    TBS = "TBS", "TBS · Tablets"
    TGM = "TGM", "TGM · Ten gross"
    THD = "THD", "THD · Thousands"
    TON = "TON", "TON · Tonnes"
    TUB = "TUB", "TUB · Tubes"
    UGS = "UGS", "UGS · US gallons"
    UNT = "UNT", "UNT · Units"
    YDS = "YDS", "YDS · Yards"
