# Generated by Django 6.1.1 on 2026-09-21 09:29

import apps.core.fields
from django.db import migrations

MODELS = ("business", "historicalbusiness")


def join_lines(apps, schema_editor):
    for name in MODELS:
        model = apps.get_model("business", name)
        rows = list(model.objects.all())
        for row in rows:
            lines = [row.address_line_1, row.address_line_2]
            row.address = "\n".join(line for line in lines if line)
        model.objects.bulk_update(rows, ["address"])


def split_lines(apps, schema_editor):
    for name in MODELS:
        model = apps.get_model("business", name)
        rows = list(model.objects.all())
        for row in rows:
            line_1, _, line_2 = row.address.partition("\n")
            if len(line_1) > 255 or len(line_2) > 255:
                # Postgres would truncate each column silently. Cutting at the
                # column's width instead keeps every character, because an
                # address is at most 500 and the two columns hold 510.
                line_1, line_2 = row.address[:255], row.address[255:]
            row.address_line_1, row.address_line_2 = line_1, line_2
        model.objects.bulk_update(rows, ["address_line_1", "address_line_2"])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=apps.core.fields.AddressField(blank=True, help_text='Building, street and area, one per line, as it should print.'),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='address',
            field=apps.core.fields.AddressField(blank=True, help_text='Building, street and area, one per line, as it should print.'),
        ),
        migrations.RunPython(join_lines, split_lines),
        migrations.RemoveField(
            model_name='business',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='business',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='historicalbusiness',
            name='address_line_2',
        ),
    ]
