# Generated by Django 6.1.1 on 2026-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='stock_start_date',
            field=models.DateField(blank=True, help_text='Stock is counted from this day. Leave blank to count none yet.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='stock_start_date',
            field=models.DateField(blank=True, help_text='Stock is counted from this day. Leave blank to count none yet.', null=True),
        ),
    ]
