# Generated by Django 6.1.1 on 2026-09-21 22:07

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, choices=[('goods', 'Goods'), ('service', 'Service')], max_length=7)),
                ('hsn_sac', models.CharField(blank=True, help_text='An HSN code of 4, 6 or 8 digits for Goods, or a SAC for a Service.', max_length=8, verbose_name='HSN/SAC code')),
                ('gst_rate', models.DecimalField(blank=True, choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('18.00'), '18%'), (Decimal('40.00'), '40%')], decimal_places=2, max_digits=4, null=True, verbose_name='GST rate')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Item code')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, choices=[('goods', 'Goods'), ('service', 'Service')], max_length=7)),
                ('hsn_sac', models.CharField(blank=True, help_text='An HSN code of 4, 6 or 8 digits for Goods, or a SAC for a Service.', max_length=8, verbose_name='HSN/SAC code')),
                ('gst_rate', models.DecimalField(blank=True, choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('18.00'), '18%'), (Decimal('40.00'), '40%')], decimal_places=2, max_digits=4, null=True, verbose_name='GST rate')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Item code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('code',), name='one_item_per_code')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemUnit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uqc', models.CharField(choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3, verbose_name='unit')),
                ('rate', models.DecimalField(decimal_places=6, default=1, help_text='How many of the stock unit one of this unit holds.', max_digits=18)),
                ('is_stock_unit', models.BooleanField(default=False)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Including GST.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogue.item')),
            ],
            options={
                'verbose_name': 'historical item unit',
                'verbose_name_plural': 'historical item units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqc', models.CharField(choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3, verbose_name='unit')),
                ('rate', models.DecimalField(decimal_places=6, default=1, help_text='How many of the stock unit one of this unit holds.', max_digits=18)),
                ('is_stock_unit', models.BooleanField(default=False)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Including GST.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='catalogue.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'uqc'), name='one_row_per_unit'), models.UniqueConstraint(condition=models.Q(('is_stock_unit', True)), fields=('item',), name='one_stock_unit_per_item'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='unit_rate_is_positive'), models.CheckConstraint(condition=models.Q(models.Q(('is_stock_unit', True), _negated=True), ('rate', 1), _connector='OR'), name='stock_unit_rate_is_one')],
            },
        ),
    ]
