# Generated by Django 6.1.1 on 2026-09-21 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='code',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'An Item code is capital letters, digits and hyphens.')], verbose_name='Item code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'An Item code is capital letters, digits and hyphens.')], verbose_name='Item code'),
        ),
    ]
