import apps.catalogue.models
import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_item_code_is_printable"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="itemunit", name="one_row_per_unit"),
        migrations.RenameField(model_name="itemunit", old_name="uqc", new_name="code"),
        migrations.RenameField(
            model_name="historicalitemunit", old_name="uqc", new_name="code"
        ),
        migrations.AlterField(
            model_name="historicalitemunit",
            name="code",
            field=models.CharField(
                choices=[
                    ("BAG", "BAG · Bags"),
                    ("BAL", "BAL · Bale"),
                    ("BDL", "BDL · Bundles"),
                    ("BKL", "BKL · Buckles"),
                    ("BOU", "BOU · Billions of units"),
                    ("BOX", "BOX · Box"),
                    ("BTL", "BTL · Bottles"),
                    ("BUN", "BUN · Bunches"),
                    ("CAN", "CAN · Cans"),
                    ("CBM", "CBM · Cubic metres"),
                    ("CCM", "CCM · Cubic centimetres"),
                    ("CMS", "CMS · Centimetres"),
                    ("CTN", "CTN · Cartons"),
                    ("DOZ", "DOZ · Dozens"),
                    ("DRM", "DRM · Drums"),
                    ("ft", "ft · Feet"),
                    ("GGK", "GGK · Great gross"),
                    ("GMS", "GMS · Grammes"),
                    ("GRS", "GRS · Gross"),
                    ("GYD", "GYD · Gross yards"),
                    ("in", "in · Inches"),
                    ("KGS", "KGS · Kilograms"),
                    ("KLR", "KLR · Kilolitres"),
                    ("KME", "KME · Kilometres"),
                    ("LTR", "LTR · Litres"),
                    ("MLT", "MLT · Millilitres"),
                    ("MTR", "MTR · Metres"),
                    ("MTS", "MTS · Metric tons"),
                    ("NOS", "NOS · Numbers"),
                    ("OTH", "OTH · Others"),
                    ("PAC", "PAC · Packs"),
                    ("PCS", "PCS · Pieces"),
                    ("PRS", "PRS · Pairs"),
                    ("QTL", "QTL · Quintals"),
                    ("ROL", "ROL · Rolls"),
                    ("SET", "SET · Sets"),
                    ("SQF", "SQF · Square feet"),
                    ("SQM", "SQM · Square metres"),
                    ("SQY", "SQY · Square yards"),
                    ("TBS", "TBS · Tablets"),
                    ("TGM", "TGM · Ten gross"),
                    ("THD", "THD · Thousands"),
                    ("TON", "TON · Tonnes"),
                    ("TUB", "TUB · Tubes"),
                    ("UGS", "UGS · US gallons"),
                    ("UNT", "UNT · Units"),
                    ("YDS", "YDS · Yards"),
                ],
                max_length=3,
                verbose_name="unit",
            ),
        ),
        migrations.AlterField(
            model_name="historicalitemunit",
            name="rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="How many of the stock unit one of this unit holds.",
                max_digits=18,
                validators=[apps.catalogue.models.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="itemunit",
            name="code",
            field=models.CharField(
                choices=[
                    ("BAG", "BAG · Bags"),
                    ("BAL", "BAL · Bale"),
                    ("BDL", "BDL · Bundles"),
                    ("BKL", "BKL · Buckles"),
                    ("BOU", "BOU · Billions of units"),
                    ("BOX", "BOX · Box"),
                    ("BTL", "BTL · Bottles"),
                    ("BUN", "BUN · Bunches"),
                    ("CAN", "CAN · Cans"),
                    ("CBM", "CBM · Cubic metres"),
                    ("CCM", "CCM · Cubic centimetres"),
                    ("CMS", "CMS · Centimetres"),
                    ("CTN", "CTN · Cartons"),
                    ("DOZ", "DOZ · Dozens"),
                    ("DRM", "DRM · Drums"),
                    ("ft", "ft · Feet"),
                    ("GGK", "GGK · Great gross"),
                    ("GMS", "GMS · Grammes"),
                    ("GRS", "GRS · Gross"),
                    ("GYD", "GYD · Gross yards"),
                    ("in", "in · Inches"),
                    ("KGS", "KGS · Kilograms"),
                    ("KLR", "KLR · Kilolitres"),
                    ("KME", "KME · Kilometres"),
                    ("LTR", "LTR · Litres"),
                    ("MLT", "MLT · Millilitres"),
                    ("MTR", "MTR · Metres"),
                    ("MTS", "MTS · Metric tons"),
                    ("NOS", "NOS · Numbers"),
                    ("OTH", "OTH · Others"),
                    ("PAC", "PAC · Packs"),
                    ("PCS", "PCS · Pieces"),
                    ("PRS", "PRS · Pairs"),
                    ("QTL", "QTL · Quintals"),
                    ("ROL", "ROL · Rolls"),
                    ("SET", "SET · Sets"),
                    ("SQF", "SQF · Square feet"),
                    ("SQM", "SQM · Square metres"),
                    ("SQY", "SQY · Square yards"),
                    ("TBS", "TBS · Tablets"),
                    ("TGM", "TGM · Ten gross"),
                    ("THD", "THD · Thousands"),
                    ("TON", "TON · Tonnes"),
                    ("TUB", "TUB · Tubes"),
                    ("UGS", "UGS · US gallons"),
                    ("UNT", "UNT · Units"),
                    ("YDS", "YDS · Yards"),
                ],
                max_length=3,
                verbose_name="unit",
            ),
        ),
        migrations.AlterField(
            model_name="itemunit",
            name="rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="How many of the stock unit one of this unit holds.",
                max_digits=18,
                validators=[apps.catalogue.models.validate_positive],
            ),
        ),
        migrations.AddConstraint(
            model_name="itemunit",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("item", "code"),
                name="one_row_per_unit",
            ),
        ),
    ]
