# Generated by Django 6.1.1 on 2026-09-22 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_units_beyond_the_gst_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemunit',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='MRP'),
        ),
    ]
