# Generated by Django 6.1.1 on 2026-09-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',), 'permissions': [('archive_item', 'Can archive item')]},
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
