# Generated by Django 6.1.1 on 2026-09-22 08:13

import apps.purchases.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0007_archived_items'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Exactly as the Supplier printed it.', max_length=32)),
                ('bill_date', models.DateField(help_text='As printed on the bill.')),
                ('received_date', models.DateField(help_text='The day the Goods arrived. Leave blank if it is the bill date.')),
                ('supplier_gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('supplier_state', models.CharField(blank=True, choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chandigarh'), ('05', 'Uttarakhand'), ('06', 'Haryana'), ('07', 'Delhi'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'Mizoram'), ('16', 'Tripura'), ('17', 'Meghalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'Odisha'), ('22', 'Chhattisgarh'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('27', 'Maharashtra'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'Lakshadweep'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'Puducherry'), ('35', 'Andaman and Nicobar Islands'), ('36', 'Telangana'), ('37', 'Andhra Pradesh'), ('38', 'Ladakh'), ('97', 'Other Territory')], help_text="The Supplier's state when the Purchase was recorded.", max_length=2)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'historical purchase',
                'verbose_name_plural': 'historical purchases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Exactly as the Supplier printed it.', max_length=32)),
                ('bill_date', models.DateField(help_text='As printed on the bill.')),
                ('received_date', models.DateField(help_text='The day the Goods arrived. Leave blank if it is the bill date.')),
                ('supplier_gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('supplier_state', models.CharField(blank=True, choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chandigarh'), ('05', 'Uttarakhand'), ('06', 'Haryana'), ('07', 'Delhi'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'Mizoram'), ('16', 'Tripura'), ('17', 'Meghalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'Odisha'), ('22', 'Chhattisgarh'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('27', 'Maharashtra'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'Lakshadweep'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'Puducherry'), ('35', 'Andaman and Nicobar Islands'), ('36', 'Telangana'), ('37', 'Andhra Pradesh'), ('38', 'Ladakh'), ('97', 'Other Territory')], help_text="The Supplier's state when the Purchase was recorded.", max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-received_date', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('unit', models.CharField(choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('ft', 'ft · Feet'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('in', 'in · Inches'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3)),
                ('stock_units_in_one', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[apps.purchases.models.validate_positive])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('18.00'), '18%'), (Decimal('40.00'), '40%')], decimal_places=2, max_digits=4, verbose_name='GST rate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalogue.item')),
                ('purchase', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchases.purchase')),
            ],
            options={
                'verbose_name': 'historical purchase line',
                'verbose_name_plural': 'historical purchase lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('ft', 'ft · Feet'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('in', 'in · Inches'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3)),
                ('stock_units_in_one', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[apps.purchases.models.validate_positive])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gst_rate', models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.25'), '0.25%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%'), (Decimal('18.00'), '18%'), (Decimal('40.00'), '40%')], decimal_places=2, max_digits=4, verbose_name='GST rate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalogue.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase')),
            ],
            options={
                'ordering': ('pk',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='line_quantity_is_positive'), models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='line_rate_is_not_negative')],
            },
        ),
    ]
