# Generated by Django 6.1.1 on 2026-09-22 08:53

import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(models.F('supplier'), models.F('bill_number'), django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.ExtractYear('bill_date'), '-', models.Case(models.When(django.db.models.lookups.LessThan(django.db.models.functions.datetime.ExtractMonth('bill_date'), 4), then=1), default=0)), name='one_bill_number_per_supplier_per_financial_year', violation_error_message='This bill is already on file.'),
        ),
    ]
