# Generated by Django 6.1.1 on 2026-09-22 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_archived_items'),
        ('purchases', '0002_one_bill_number_per_supplier_per_financial_year'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='bill_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='As printed, before tax. Leave blank if there is none.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bill_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='As printed, before tax. Leave blank if there is none.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('bill_discount__gte', 0)), name='bill_discount_is_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__range', (0, 100))), name='line_discount_is_a_percentage'),
        ),
    ]
