# Generated by Django 6.1.1 on 2026-09-22 12:00

import django.core.validators
from django.db import migrations, models

from apps.purchases.totals import Line, purchase_totals


def bill_as_billow_totals_it(apps, schema_editor):
    # Nothing was typed off the bills already on file, so each is taken to
    # have said what billow made it, which is what it showed until now.
    Business = apps.get_model("business", "Business")
    Purchase = apps.get_model("purchases", "Purchase")
    business = Business.objects.first()
    for purchase in Purchase.objects.all():
        totals = purchase_totals(
            [
                Line(
                    quantity=line.quantity,
                    rate=line.rate,
                    gst_rate=line.gst_rate,
                    stock_units_in_one=line.stock_units_in_one,
                    discount_percent=line.discount_percent,
                )
                for line in purchase.lines.order_by("pk")
            ],
            supplier_state=purchase.supplier_state,
            supplier_gstin=purchase.supplier_gstin,
            business_state=business.state,
            business_registered=bool(business.is_gst_registered),
            bill_discount=purchase.bill_discount,
        )
        purchase.billed_total = totals.grand_total
        purchase.save(update_fields=["billed_total"])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_address'),
        ('purchases', '0003_discounts'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='billed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Grand total on the bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Leave blank for the one that makes a whole rupee.', max_digits=3, validators=[django.core.validators.MinValueValidator(-1, 'A Round-off is no more than ₹1.00 either way.'), django.core.validators.MaxValueValidator(1, 'A Round-off is no more than ₹1.00 either way.')], verbose_name='Round-off'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='billed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Grand total on the bill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Leave blank for the one that makes a whole rupee.', max_digits=3, validators=[django.core.validators.MinValueValidator(-1, 'A Round-off is no more than ₹1.00 either way.'), django.core.validators.MaxValueValidator(1, 'A Round-off is no more than ₹1.00 either way.')], verbose_name='Round-off'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('round_off__range', (-1, 1))), name='round_off_is_within_a_rupee'),
        ),
        migrations.RunPython(bill_as_billow_totals_it, migrations.RunPython.noop),
    ]
