# Generated by Django 6.1.1 on 2026-09-22 12:32

import apps.tax.hsn_sac
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_archived_items'),
        ('purchases', '0004_round_off_and_billed_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=8, validators=[apps.tax.hsn_sac.validate_hsn_or_sac], verbose_name='HSN or SAC'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseline',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=8, validators=[apps.tax.hsn_sac.validate_hsn_or_sac], verbose_name='HSN or SAC'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='stock_units_in_one',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseline',
            name='unit',
            field=models.CharField(blank=True, choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('ft', 'ft · Feet'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('in', 'in · Inches'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='stock_units_in_one',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit',
            field=models.CharField(blank=True, choices=[('BAG', 'BAG · Bags'), ('BAL', 'BAL · Bale'), ('BDL', 'BDL · Bundles'), ('BKL', 'BKL · Buckles'), ('BOU', 'BOU · Billions of units'), ('BOX', 'BOX · Box'), ('BTL', 'BTL · Bottles'), ('BUN', 'BUN · Bunches'), ('CAN', 'CAN · Cans'), ('CBM', 'CBM · Cubic metres'), ('CCM', 'CCM · Cubic centimetres'), ('CMS', 'CMS · Centimetres'), ('CTN', 'CTN · Cartons'), ('DOZ', 'DOZ · Dozens'), ('DRM', 'DRM · Drums'), ('ft', 'ft · Feet'), ('GGK', 'GGK · Great gross'), ('GMS', 'GMS · Grammes'), ('GRS', 'GRS · Gross'), ('GYD', 'GYD · Gross yards'), ('in', 'in · Inches'), ('KGS', 'KGS · Kilograms'), ('KLR', 'KLR · Kilolitres'), ('KME', 'KME · Kilometres'), ('LTR', 'LTR · Litres'), ('MLT', 'MLT · Millilitres'), ('MTR', 'MTR · Metres'), ('MTS', 'MTS · Metric tons'), ('NOS', 'NOS · Numbers'), ('OTH', 'OTH · Others'), ('PAC', 'PAC · Packs'), ('PCS', 'PCS · Pieces'), ('PRS', 'PRS · Pairs'), ('QTL', 'QTL · Quintals'), ('ROL', 'ROL · Rolls'), ('SET', 'SET · Sets'), ('SQF', 'SQF · Square feet'), ('SQM', 'SQM · Square metres'), ('SQY', 'SQY · Square yards'), ('TBS', 'TBS · Tablets'), ('TGM', 'TGM · Ten gross'), ('THD', 'THD · Thousands'), ('TON', 'TON · Tonnes'), ('TUB', 'TUB · Tubes'), ('UGS', 'UGS · US gallons'), ('UNT', 'UNT · Units'), ('YDS', 'YDS · Yards')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hsn_sac', ''), ('item__isnull', False), ('name', '')), models.Q(('item__isnull', True), ('unit', ''), models.Q(('name', ''), _negated=True), models.Q(('hsn_sac', ''), _negated=True)), _connector='OR'), name='line_is_an_item_or_one_off'),
        ),
    ]
